# =============================================
# colors.toml - Catppuccin Mocha
# =============================================

mode = "dark"

accent = "#f5c2e7"
selection = "#f5e0dc"
muted = "#585b70"

background = "#11111b"
dark_background = "#0b0b12"
darker_background = "#07070c"
lighter_background = "#1e1e2e"

foreground = "#cdd6f4"
dark_foreground = "#6c7086"
light_foreground = "#bac2de"
bright_foreground = "#f5e0dc"

red = "#f38ba8"
yellow = "#f9e2af"
orange = "#fab387"
green = "#a6e3a1"
cyan = "#94e2d5"
blue = "#89b4fa"
magenta = "#f5c2e7"
brown = "#7b5b55"

bright_red = "#f38ba8"
bright_yellow = "#f9e2af"
bright_green = "#a6e3a1"
bright_cyan = "#94e2d5"
bright_blue = "#89b4fa"
bright_magenta = "#f5c2e7"
