$activeBorderColor = rgba(89b4faee) rgba(F5C2E7ee) 25deg
$inactiveBorderColor = rgba(89b4fa80) rgba(F5C2E780) 25deg

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor

    gaps_in = 4
    gaps_out = 8
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    col.border_locked_active = $activeBorderColor
    col.border_locked_inactive = $inactiveBorderColor

    groupbar {
        font_size = 12
        font_family = JetBrainsMono Nerd Font
        font_weight_active = bold
        font_weight_inactive = normal

        indicator_height = 0
        indicator_gap = 5
        height = 24
        gaps_in = 5
        gaps_out = 0

        text_color = rgb(cdd6f4)
        text_color_inactive = rgba(a6adc890)
        col.active = rgba(000000cc)
        col.inactive = rgba(1e1e2e66)

        gradients = true
        gradient_rounding = 4
        gradient_round_only_edges = true
    }
}

animations {
    enabled = true

    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    bezier = water, 0.22, 0.9, 0.36, 1.0
    bezier = flow, 0.25, 0.1, 0.25, 1.0
    bezier = ripple, 0.33, 0.0, 0.2, 1.0
    bezier = cascade, 0.19, 1.0, 0.22, 1.0
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade,       1, 2.4, water
    animation = fadeIn,     1, 2.0, cascade
    animation = fadeOut,    1, 1.8, ripple
    animation = fadeDim,    1, 2.0, water
    animation = fadeSwitch, 1, 1.4, flow
    animation = layersIn,       1, 1.5, overshot, popin 80%
    animation = layersOut,      1, 1.3, md3_accel, popin 90%
    animation = layers,         1, 1.5, md3_standard
    animation = workspaces, 1, 5, wind
}

decoration {
    rounding = 4
    rounding_power = 4.0

    dim_inactive = true
    dim_strength = 0.02

    active_opacity = 0.98
    inactive_opacity = 0.94
    fullscreen_opacity = 1

    blur {
        size = 6
        passes = 3
        xray = false
        noise = 0
        contrast = 1
    }

    shadow {
        enabled = true
        range = 16
        scale = 1.0
        render_power = 4
        offset = 0 2
        color = rgba(11111b78)
        color_inactive = rgba(11111b40)
    }
}

misc {
  animate_manual_resizes = true
  animate_mouse_windowdragging = true
}

cursor {
  inactive_timeout = 10
}

