# =============================================
# hyprland.conf - Catppuccin Mocha
# =============================================

$activeBorderColor = rgba(89b4faee) rgba(f5c2e7ee) 25deg
$inactiveBorderColor = rgba(89b4fa80) rgba(f5c2e780) 25deg

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    col.border_locked_active = $activeBorderColor
    col.border_locked_inactive = $inactiveBorderColor
}
