# Base colors
background              #1e1e2e
foreground              #cdd6f4

background_opacity 0.6

cursor                  #89b4fa
cursor_text_color       #1e1e2e
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_shape underline
cursor_shape_unfocused unchanged
cursor_blink_interval 0
shell_integration no-cursor

title_fg                #cdd6f4
title_bg                #181825
margin_bg               #181825
margin_fg               #a6adc8
filler_bg               #181825

url_color               #89b4fa

selection_foreground    #1e1e2e
selection_background    #89b4fa

visual_bell_color       #f9e2af

removed_bg              #5e3f53
highlight_removed_bg    #89556b
removed_margin_bg       #734a5f

added_bg                #475a51
highlight_added_bg      #628168
added_margin_bg         #5e7a6a

hunk_margin_bg          #181825
hunk_bg                 #2a2b3c

# Search
search_fg               #1e1e2e
search_bg               #f9e2af

# black
color0                  #1e1e2e
color8                  #585b70

# red
color1                  #f38ba8
color9                  #f38ba8

# green
color2                  #a6e3a1
color10                 #a6e3a1

# yellow
color3                  #f9e2af
color11                 #f9e2af

# blue
color4                  #89b4fa
color12                 #89b4fa

# magenta
color5                  #f5c2e7
color13                 #f5c2e7

# cyan
color6                  #94e2d5
color14                 #94e2d5

# white
color7                  #cdd6f4
color15                 #cdd6f4

